services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    container_name: donetick-postgres
    hostname: donetick-postgres
    restart: unless-stopped
    env_file:
      - .env.secrets
      - .env
    volumes:
      - /data/container-configs/donetick/db:/var/lib/postgresql/data

  donetick:
    image: donetick/donetick:${DT_IMAGE_TAG}
    container_name: donetick
    hostname: donetick
    restart: unless-stopped
    ports:
      - 2021:2021
    volumes:
      # - ./data:/donetick-data
      - /data/container-configs/donetick/config:/config
    env_file:
      - .env.secrets
      - .env
    depends_on:
      - postgres

  newt:
    image: fosrl/newt
    container_name: donetick-newt
    hostname: donetick-newt
    restart: unless-stopped
    env_file:
      - .env.secrets
    depends_on:
      - donetick

volumes:
  postgres_data: