version: "3"
services:
  tasks.md:
    image: baldissaramatheus/tasks.md
    container_name: tasks.md
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./tasks:/tasks
      - ./files:/config
    restart: unless-stopped
    ports:
      - 8080:8080